# Generated by Django 5.0.7 on 2024-08-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_image_urls_featurepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_content',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='feature_image_url',
            field=models.CharField(default=' ', max_length=5000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeaturePost',
        ),
    ]
