# Generated by Django 5.0.7 on 2024-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_feature_content_post_feature_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_image_url',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_urls',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
