# Generated by Django 5.1.7 on 2025-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='feature_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
