# Generated by Django 5.1.7 on 2025-04-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_content_image_remove_post_feature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('header', 'Header'), ('text', 'Text'), ('image', 'Image')], max_length=10),
        ),
    ]
