# Generated by Django 5.1.7 on 2025-04-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_content_header_alter_content_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_url',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.image'),
        ),
    ]
