# Generated by Django 5.1.7 on 2025-05-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_alter_comment_options_comment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='order',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
