# Generated by Django 5.1.7 on 2025-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_alter_comment_options_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='subheader',
            field=models.TextField(blank=True, null=True),
        ),
    ]
