# Generated by Django 5.1.7 on 2025-05-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_content_subheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('header', 'Header'), ('subheader', 'Subheader'), ('text', 'Text'), ('image', 'Image')], max_length=10),
        ),
    ]
