# Generated by Django 5.1.7 on 2025-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('header', 'Header'), ('subheader', 'Subheader'), ('text', 'Text'), ('link', 'Link'), ('image', 'Image')], max_length=10),
        ),
    ]
