# Generated by Django 5.1.7 on 2025-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_content_link_alter_content_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.AddField(
            model_name='content',
            name='link_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='link_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
